### ISSUE TITLE
Select Query Example

### ISSUE THREAD

**Issue by peymanmajidi** [mustafakemalgilor/arduino-mssql#1]
Thanks for your great job
I can insert data to DB but I don't know how to select query.
How to see the result of the "select" query?
can u give me an example??
Thanks for your response.

**Comment by xmkg** [comment]
Example taken from : https://github.com/mustafakemalgilor/arduino-mssql/blob/master/sqlard-test.cpp

 ```cpp
SQLardTableResult * tr = MSSQL.executeReader(L"SELECT water_enable FROM ROOM_STATUS WHERE dnd_guid = '4567A1FF-3790-4519-83EE-A709A59E238F'");
 
// executes a select query, and returns a cursor (or iterator) to result.
```

You can access current row by  calling GetRow function. (`tr->GetRow()`)
You can move to next row by calling MoveNext function. (`tr->MoveNext()`)
