### ISSUE TITLE
Is it possible at UNO board?

### ISSUE THREAD

**Issue by jjuny-Park** [mustafakemalgilor/arduino-mssql#5]
thank you,

I'm trying....

Compile error occurs.

OS : Windows 10
BOARD : Arduino UNO R3 + Ethernet Shield

Is it possible at UNO board?

**Comment by xmkg** [comment]
Yes, it is possible.

**Comment by jjuny-Park** [comment]
I'm a beginner in developing Arduino.
Please give me some advice.

error message 1 : In file included from ...  UIPEthernet/utility/mempool_conf.h:5:0,
                                                                   UIPEthernet/utility/mempool.h:28
                                                                   similar message....
error message 2 : #warning "Endianness configured automaticaly."
error message 3 : More verbosity more memory usage

I'd appreciate your help.
