### ISSUE TITLE
Question about SELECT QUERY

### ISSUE THREAD

**Issue by jjuny-Park** [mustafakemalgilor/arduino-mssql#6]
Thank you for your inspiration

DB connection, INSERT, UPDATE, DELETE has been successful.

I'm trying to SELECT QUERY, but I'm not sure.

I'd appreciate your help.

**Comment by xmkg** [comment]
Take a look into https://github.com/mustafakemalgilor/arduino-mssql/blob/master/sqlard-test.cpp . It might give you an idea.
