### ISSUE TITLE
what's happened with my code

### ISSUE THREAD

**Issue by Jkrvalho** [mustafakemalgilor/arduino-mssql#8]
When I try to compile my code in Arduino IDE the error occurs

In file included from D:\Projetos\IDPCT400A_com_ESP8266\sqlard_test\sqlard_test.ino:1:
C:\Users\PC\OneDrive\Documentos\Arduino\libraries\arduino-mssql-master/sqlard.h: In member function 'bool SQLard::login()':
C:\Users\PC\OneDrive\Documentos\Arduino\libraries\arduino-mssql-master/sqlard.h:1144:11: error: section attribute cannot be specified for local variables
 1144 |   uint8_t data[256] PROGMEM;
      |           ^~~~
exit status 1
Erro compilando para a placa NodeMCU 1.0 (ESP-12E Module)

Thanks

**Comment by xmkg** [comment]
Probably your toolchain/board does not have PROGMEM available in a way that Arduino specifies.
